# YouTube Feed Workflow
# This workflow updates the README with the latest YouTube videos from a specified channel.
# @copyright   (c) Pierre-Henry Soria <https://ph7.me>
# @license     MIT <https://opensource.org/license/mit>

name: Latest Programming Videos
on:
  schedule:
    # Runs every day at 00:00 UTC 
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in YouTube videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'YOUTUBE'
          max_post_count: 8
          title_max_length: 75
          commit_message: 'Update README with 7 latest YouTube videos'
          feed_list: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCGqLuT0upPiocwYSnnmqt2g'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
